# Generated by Django 4.0.3 on 2022-08-09 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gantt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gantt.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gantt.project'),
        ),
        migrations.AddField(
            model_name='state',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gantt.project'),
        ),
        migrations.AddField(
            model_name='role',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gantt.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gantt.activity'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assigned',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gantt.activity'),
        ),
        migrations.AddField(
            model_name='assigned',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='dependency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='gantt.activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gantt.state'),
        ),
        migrations.AddField(
            model_name='activity',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gantt.task'),
        ),
        migrations.CreateModel(
            name='ChertActivity',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gantt.activity',),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='unique_team_employee'),
        ),
        migrations.AddConstraint(
            model_name='assigned',
            constraint=models.UniqueConstraint(fields=('activity', 'user'), name='unique_activity_user'),
        ),

    ]
